# Generated by Django 4.0.1 on 2022-05-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_auth', '0002_user_last_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('IM', 'Inventory Manager'), ('SM', 'Storage Manager'), ('SE', 'Storage Employee'), ('DE', 'Data Employee')], default='SE', max_length=2),
        ),
    ]
