# Generated by Django 4.0.1 on 2022-08-05 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra_custom', '0008_productsku_is_valid'),
        ('infra_auth', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra_custom.location')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(related_name='users', related_query_name='user', through='infra_auth.UserLocation', to='infra_custom.Location'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
