# Generated by Django 4.0.1 on 2022-06-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra_custom', '0004_category_categoryattribute_category_attributes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
