# Generated by Django 4.0.1 on 2022-06-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_custom', '0006_product_alter_location_options_productsku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(related_name='categories', through='infra_custom.CategoryAttribute', to='infra_custom.Attribute'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(related_name='products', through='infra_custom.ProductAttribute', to='infra_custom.Attribute'),
        ),
    ]
