# Generated by Django 4.0.1 on 2022-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_custom', '0007_alter_category_attributes_alter_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
