from .attribute_views import AttributesListView, AttributesView, AttributesDeleteView
from .attribute_value_views import AttributeValuesListView, AttributeValuesView, AttributeValuesDeleteView
from .location_level_views import LocationLevelsListView, LocationLevelView
from .location_views import LocationsListView, LocationsView
